name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Install build requirements
        run: |
          cd build
          pixi install

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      # Note not sure why this is needed
      - name: Install protobuf
        run: |
          sudo apt-get install libprotobuf-dev protobuf-compiler

      - run: sudo apt install libgeos-dev

      # Don't use --all-features as we don't have GDAL 3.6 available in CI
      - name: "clippy --all"
        run: cargo clippy --all --all-features --tests -- -D warnings

      - name: "cargo check"
        run: cargo check --all --all-features

      - name: "cargo test"
        run: |
          cargo test --all
          cargo test --all --all-features
